[project]
name = 'Tokenized-Retail-Customer-Insights-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consent-management]
path = 'contracts/consent-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.data-collection]
path = 'contracts/data-collection.clar'
clarity_version = 2
epoch = 2.5

[contracts.monetization]
path = 'contracts/monetization.clar'
clarity_version = 2
epoch = 2.5

[contracts.vehicle-verification]
path = 'contracts/vehicle-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
